import { Audio } from "@remotion/media";
import {
  AbsoluteFill,
  Easing,
  Sequence,
  interpolate,
  spring,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";

type Phone = "iphone" | "galaxy";
type Shot = "hero" | "category" | "counter" | "quran" | "prayer" | "qibla" | "favorite" | "settings" | "closing";

const emerald = "#10B981";
const gold = "#D6B56B";
const paper = "#FBF8F1";
const dark = "#091914";
const ui = "AlMufradunUI, sans-serif";
const nasakh = "AlMufradunNasakh, serif";
const quran = "AlMufradunQuran, serif";
const base: React.CSSProperties = { position: "absolute", inset: 0, overflow: "hidden", fontFamily: ui, WebkitFontSmoothing: "antialiased" };

const clamp = (n: number) => Math.min(1, Math.max(0, n));
const ease = (frame: number, start: number, end: number) => interpolate(clamp((frame - start) / (end - start)), [0, 1], [0, 1], { easing: Easing.bezier(0.16, 1, 0.3, 1) });
const shotAt = (f: number): Shot => f < 240 ? "hero" : f < 480 ? "category" : f < 720 ? "counter" : f < 1020 ? "quran" : f < 1320 ? "prayer" : f < 1560 ? "qibla" : f < 1800 ? "favorite" : f < 2100 ? "settings" : "closing";

const Brand = ({ size = 28, reverse = false }: { size?: number; reverse?: boolean }) => (
  <div style={{ display: "flex", direction: "rtl", gap: size * 0.25, alignItems: "center" }}>
    <div style={{ width: size, height: size, borderRadius: size * 0.32, position: "relative", background: `linear-gradient(145deg, ${emerald}, #0B7254)`, boxShadow: `0 5px 18px ${emerald}55` }}><span style={{ position: "absolute", inset: size * 0.17, border: `${Math.max(1, size * 0.055)}px solid ${gold}`, borderRadius: size * 0.23 }} /><span style={{ position: "absolute", top: size * 0.32, left: size * 0.26, width: size * 0.45, borderBottom: `${Math.max(1, size * 0.055)}px solid ${gold}`, transform: "rotate(-38deg)" }} /></div>
    <span style={{ color: reverse ? paper : dark, fontFamily: ui, fontWeight: 900, fontSize: size * 0.82, lineHeight: 1 }}>المفردون</span>
  </div>
);

const Ring = ({ value, size, title, note }: { value: number; size: number; title: string; note?: string }) => {
  const stroke = Math.max(5, size * 0.09); const r = (size - stroke) / 2; const c = Math.PI * 2 * r;
  return <div style={{ width: size, height: size, position: "relative", display: "grid", placeItems: "center" }}><svg width={size} height={size} style={{ position: "absolute", transform: "rotate(-90deg)" }}><circle cx={size / 2} cy={size / 2} r={r} fill="none" stroke="#DDF0E9" strokeWidth={stroke} /><circle cx={size / 2} cy={size / 2} r={r} fill="none" stroke={emerald} strokeWidth={stroke} strokeLinecap="round" strokeDasharray={c} strokeDashoffset={c * (1 - value)} /></svg><div style={{ textAlign: "center", color: dark, lineHeight: 1, zIndex: 1, fontFamily: ui }}><div style={{ fontSize: size * 0.25, fontWeight: 900 }}>{title}</div>{note ? <div style={{ marginTop: 3, color: "#728079", fontSize: size * 0.1, fontWeight: 700 }}>{note}</div> : null}</div></div>;
};

const Nav = ({ active }: { active: number }) => {
  const tabs = [["⌂", "الرئيسية"], ["▤", "القرآن"], ["◈", "القبلة"], ["♡", "المفضلة"], ["◷", "المواقيت"], ["⚙", "الإعدادات"]];
  return <div style={{ position: "absolute", bottom: 0, left: 0, right: 0, height: 71, padding: "8px 10px", display: "flex", justifyContent: "space-between", alignItems: "flex-start", direction: "rtl", background: "#FFFDFC", borderTop: "1px solid #D9E3DE" }}>{tabs.map(([i, t], n) => <div key={t} style={{ width: "16.6%", textAlign: "center", color: active === n ? emerald : "#7B8983", fontFamily: ui, fontWeight: active === n ? 900 : 600, fontSize: 8 }}><div style={{ width: active === n ? 28 : 20, height: 20, margin: "0 auto 3px", borderRadius: 10, background: active === n ? "#DCF8ED" : "transparent", fontSize: 15, lineHeight: "20px" }}>{i}</div>{t}</div>)}</div>;
};

const List = ({ icon, title, sub, heart = false }: { icon: string; title: string; sub: string; heart?: boolean }) => <div style={{ height: 49, padding: "0 11px", display: "flex", direction: "rtl", gap: 10, alignItems: "center", background: "#FFFFFF", borderRadius: 14, border: "1px solid #E9F0EC", boxShadow: "0 3px 11px #163A2810" }}><div style={{ width: 28, height: 28, borderRadius: 10, display: "grid", placeItems: "center", background: heart ? "#FFF0F0" : "#E7F7F0", color: heart ? "#E04E62" : emerald, fontSize: 15 }}>{icon}</div><div style={{ flex: 1 }}><div style={{ fontFamily: ui, color: dark, fontWeight: 800, fontSize: 11 }}>{title}</div><div style={{ marginTop: 2, fontFamily: ui, color: "#81918A", fontWeight: 600, fontSize: 8 }}>{sub}</div></div><span style={{ color: "#9FB0A8", fontSize: 14 }}>‹</span></div>;

const Home = ({ frame }: { frame: number }) => {
  const pulse = 0.44 + Math.sin(frame / 13) * 0.14;
  const card = (moon: boolean, title: string, sub: string) => <div style={{ height: 96, padding: "13px 12px", boxSizing: "border-box", overflow: "hidden", position: "relative", borderRadius: 18, color: "white", background: moon ? "linear-gradient(145deg, #133E37, #0A241E)" : "linear-gradient(145deg, #19BA89, #0F8E69)", boxShadow: `0 10px 24px ${moon ? "#0C362A" : emerald}${Math.round(pulse * 85).toString(16).padStart(2, "0")}` }}><div style={{ position: "absolute", width: 60, height: 60, left: -8, top: -18, borderRadius: 40, background: "#FFFFFF", opacity: 0.09 }} /><span style={{ fontSize: 21 }}>{moon ? "☾" : "☼"}</span><div style={{ marginTop: 6, fontFamily: ui, fontWeight: 900, fontSize: 13 }}>{title}</div><div style={{ marginTop: 3, fontFamily: ui, fontWeight: 600, fontSize: 8.5, opacity: 0.82 }}>{sub}</div></div>;
  return <div style={{ ...base, background: paper, direction: "rtl" }}><div style={{ padding: "44px 21px 0" }}><div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}><Brand size={26} /><div style={{ width: 27, height: 27, borderRadius: 13, background: "#EBF6F0", color: emerald, display: "grid", placeItems: "center", fontSize: 17 }}>⌕</div></div><div style={{ marginTop: 21, color: "#6E7C75", fontFamily: ui, fontSize: 11, fontWeight: 600 }}>السلام عليكم</div><div style={{ marginTop: 3, color: dark, fontFamily: ui, fontSize: 22, fontWeight: 900 }}>وردك اليومي ينتظرك</div><div style={{ marginTop: 18, display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}>{card(false, "أذكار الصباح", "ابدأ يومك بطمأنينة")}{card(true, "أذكار المساء", "اختم يومك بسكينة")}</div><div style={{ marginTop: 19, display: "flex", justifyContent: "space-between", alignItems: "center" }}><span style={{ fontFamily: ui, fontSize: 15, fontWeight: 900, color: dark }}>أقسام الأذكار</span><span style={{ fontFamily: ui, fontSize: 10, fontWeight: 800, color: emerald }}>عرض الكل</span></div><div style={{ marginTop: 11, display: "grid", gap: 8 }}><List icon="✦" title="أذكار بعد الصلاة" sub="١١ ذكراً" /><List icon="◐" title="أذكار النوم" sub="٩ أذكار" /><List icon="♧" title="أدعية مختارة" sub="٢٢ دعاء" /></div></div><Nav active={0} /></div>;
};

export const Category = ({ frame }: { frame: number }) => {
  const p = interpolate(frame % 240, [8, 145], [0, 1], { extrapolateRight: "clamp", easing: Easing.out(Easing.cubic) });
  const dhikr = (text: string, n: string, done: boolean) => <div style={{ minHeight: 64, padding: "10px", display: "flex", direction: "rtl", gap: 10, alignItems: "center", background: "#FFFFFF", borderRadius: 15, border: `1px solid ${done ? "#BEEAD7" : "#E9F0EC"}`, boxShadow: "0 3px 11px #163A2810" }}><div style={{ width: 24, height: 24, borderRadius: 9, background: done ? emerald : "#E7F5EE", color: done ? "white" : emerald, display: "grid", placeItems: "center", fontFamily: ui, fontSize: 10, fontWeight: 900 }}>{done ? "✓" : n}</div><div style={{ flex: 1 }}><div style={{ fontFamily: nasakh, color: dark, fontSize: 15, lineHeight: 1.25 }}>{text}</div><div style={{ marginTop: 4, fontFamily: ui, color: "#84918B", fontSize: 8, fontWeight: 700 }}>مرة واحدة</div></div><span style={{ color: "#B3C1BB", fontSize: 15 }}>‹</span></div>;
  return <div style={{ ...base, background: paper, direction: "rtl" }}><div style={{ padding: "42px 21px 0" }}><div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}><span style={{ width: 30, height: 30, borderRadius: 11, background: "#FFFFFF", display: "grid", placeItems: "center", border: "1px solid #E6EEE9", fontSize: 20 }}>›</span><span style={{ fontFamily: ui, fontWeight: 900, color: dark, fontSize: 15 }}>أذكار الصباح</span><span style={{ width: 30 }} /></div><div style={{ marginTop: 18, padding: "16px", borderRadius: 21, display: "flex", gap: 15, alignItems: "center", background: "linear-gradient(135deg, #F4FFFA, #E5F9EF)", border: "1px solid #D1EEE0" }}><Ring value={p} size={74} title={`${Math.round(p * 100).toLocaleString("ar-EG")}٪`} note="اكتمال" /><div><div style={{ fontFamily: ui, fontSize: 16, color: dark, fontWeight: 900 }}>ورد الصباح</div><div style={{ marginTop: 5, fontFamily: ui, color: "#668278", fontSize: 10, fontWeight: 600 }}>سبّح قلبك في بداية يومك</div><div style={{ display: "inline-block", marginTop: 10, padding: "4px 8px", borderRadius: 8, background: "#FFFFFF", color: emerald, fontFamily: ui, fontSize: 9, fontWeight: 900 }}>١٢ من ١٢</div></div></div><div style={{ marginTop: 18, display: "grid", gap: 9 }}>{dhikr("أصبحنا وأصبح الملك لله", "١", p > 0.25)}{dhikr("اللهم بك أصبحنا وبك أمسينا", "٢", p > 0.5)}{dhikr("رضيت بالله رباً", "٣", p > 0.75)}</div></div></div>;
};

const Counter = ({ frame }: { frame: number }) => {
  const tap = Math.floor((frame % 190) / 30); const p = Math.min(1, tap / 3); const done = tap >= 3;
  return <div style={{ ...base, background: paper, direction: "rtl" }}><div style={{ opacity: 0.22 }}><Category frame={frame} /></div><div style={{ position: "absolute", inset: 0, background: "#03150C66" }} /><div style={{ position: "absolute", bottom: 0, left: 0, right: 0, height: 530, padding: "18px 22px", boxSizing: "border-box", borderRadius: "28px 28px 0 0", background: "#FFFDFC", boxShadow: "0 -15px 45px #04110B33" }}><div style={{ width: 43, height: 4, margin: "0 auto", borderRadius: 5, background: "#D9E4DE" }} /><div style={{ marginTop: 18, display: "flex", justifyContent: "space-between", alignItems: "center" }}><span style={{ color: emerald, fontFamily: ui, fontWeight: 900, fontSize: 10 }}>ذكر ٢ من ١٢</span><span style={{ width: 27, height: 27, borderRadius: 13, background: "#F0F6F2", color: "#84938C", textAlign: "center", lineHeight: "27px", fontSize: 16 }}>×</span></div><div style={{ marginTop: 24, textAlign: "center", fontFamily: nasakh, color: dark, fontSize: 24, lineHeight: 1.65 }}>سبحان الله وبحمده</div><div style={{ marginTop: 8, textAlign: "center", fontFamily: ui, color: "#7B8982", fontSize: 10, fontWeight: 700 }}>مائة مرة</div><div style={{ width: 158, height: 158, margin: "27px auto 0", position: "relative", display: "grid", placeItems: "center" }}><svg width={158} height={158} style={{ position: "absolute", transform: "rotate(-90deg)" }}><circle cx="79" cy="79" r="67" fill="none" stroke="#DDF2E8" strokeWidth="9" /><circle cx="79" cy="79" r="67" fill="none" stroke={done ? gold : emerald} strokeWidth="9" strokeLinecap="round" strokeDasharray={421} strokeDashoffset={421 * (1 - p)} /></svg><div style={{ width: 116, height: 116, display: "grid", placeItems: "center", borderRadius: 60, background: done ? "linear-gradient(145deg, #1AB786, #0A7859)" : "#F2FBF6", boxShadow: done ? "0 12px 28px #0DAA7A55" : "inset 0 0 0 1px #D6F1E3" }}><div style={{ textAlign: "center", color: done ? "white" : emerald, fontFamily: ui }}><div style={{ fontSize: 31, fontWeight: 900 }}>{done ? "✓" : Math.min(3, tap).toLocaleString("ar-EG")}</div><div style={{ marginTop: 2, fontSize: 9, fontWeight: 800 }}>{done ? "اكتمل الذكر" : "اضغط للذكر"}</div></div></div>{tap > 0 && !done ? <div style={{ position: "absolute", inset: 0, borderRadius: 100, border: "2px solid #10B981", opacity: 0.3, transform: `scale(${1 + (frame % 30) / 25})` }} /> : null}</div><div style={{ marginTop: 21, display: "flex", justifyContent: "center", gap: 6 }}>{[0, 1, 2].map((_, n) => <span key={n} style={{ width: n <= tap ? 25 : 10, height: 4, borderRadius: 4, background: n <= tap ? emerald : "#DCE8E2" }} />)}</div></div></div>;
};

const Quran = ({ frame }: { frame: number }) => {
  const sheet = frame % 300 > 165; const pageTurn = interpolate(frame % 300, [0, 90], [0, -22], { extrapolateRight: "clamp", easing: Easing.inOut(Easing.quad) });
  const verse = ["بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ ۝١", "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ ۝٢", "الرَّحْمَٰنِ الرَّحِيمِ ۝٣", "مَالِكِ يَوْمِ الدِّينِ ۝٤", "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ ۝٥", "اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ ۝٦", "صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ ۝٧"];
  return <div style={{ ...base, background: "#F8F2E7", direction: "rtl" }}><div style={{ padding: "40px 20px 0" }}><div style={{ height: 30, display: "flex", justifyContent: "space-between", alignItems: "center" }}><span style={{ color: dark, fontSize: 20 }}>⌕</span><div style={{ fontFamily: ui, fontSize: 14, fontWeight: 900, color: dark }}>سورة الفاتحة</div><span style={{ color: dark, fontSize: 19 }}>‹</span></div><div style={{ marginTop: 18, padding: 4, borderRadius: 8, border: "1px solid #D5B77A", background: "#FEFAF1" }}><div style={{ minHeight: 590, padding: "18px 16px", boxSizing: "border-box", border: "1px solid #E5C987", borderRadius: 5, background: "radial-gradient(circle at 50% 10%, #FFFDF6, #FBF3E2)" }}><div style={{ color: "#967235", textAlign: "center", fontFamily: ui, fontSize: 13, fontWeight: 900 }}>سُورَةُ الْفَاتِحَةِ</div><div style={{ width: 118, height: 1, margin: "10px auto", background: "#D8B875" }} /><div style={{ transform: `translateX(${pageTurn}px)`, fontFamily: quran, textAlign: "center", color: "#342715", fontSize: 24, lineHeight: 2.05 }}>{verse.map((v) => <div key={v} style={{ marginTop: 6 }}>{v}</div>)}</div><div style={{ marginTop: 23, textAlign: "center", color: "#A68147", fontFamily: ui, fontSize: 9, fontWeight: 800 }}>١</div></div></div></div>{sheet ? <div style={{ position: "absolute", left: 14, right: 14, bottom: 77, padding: "14px 15px", display: "flex", gap: 8, justifyContent: "space-between", background: "#FFFFFDF2", border: "1px solid #E7DBBC", borderRadius: 19, boxShadow: "0 10px 24px #3A240E22" }}>{[["▣", "نسخ"], ["↗", "مشاركة"], ["♧", "حفظ"]].map(([icon, label], n) => <div key={label} style={{ width: "33%", height: 50, display: "grid", placeItems: "center", borderRadius: 12, background: n === 1 ? "#E8F8F0" : "#F8F5EC", color: n === 1 ? emerald : "#725F36", fontFamily: ui, fontSize: 10, fontWeight: 900 }}><span style={{ fontSize: 16 }}>{icon}</span><span>{label}</span></div>)}</div> : null}<Nav active={1} /></div>;
};

const Toggle = ({ on }: { on: boolean }) => <span style={{ width: 34, height: 20, padding: 2, display: "inline-flex", alignItems: "center", justifyContent: on ? "flex-start" : "flex-end", borderRadius: 15, background: on ? emerald : "#BFC6C1", boxShadow: on ? "0 0 10px #10B98166" : "none" }}><span style={{ width: 16, height: 16, borderRadius: 12, background: "white", boxShadow: "0 1px 4px #001A10AA" }} /></span>;

const Prayer = ({ frame }: { frame: number }) => {
  const sec = 46 - Math.floor((frame % 300) / 60); const active = frame % 300 > 130;
  const prayers: [string, string, boolean][] = [["الفجر", "٥:١١", true], ["الظهر", "١٢:١٣", true], ["العصر", "٣:٣٨", active], ["المغرب", "٦:٠٢", true], ["العشاء", "٧:٢٤", false]];
  return <div style={{ ...base, background: "#F8FBF9", direction: "rtl" }}><div style={{ padding: "43px 20px 0" }}><div style={{ textAlign: "center", fontFamily: ui, color: dark, fontSize: 17, fontWeight: 900 }}>مواقيت الصلاة</div><div style={{ position: "relative", overflow: "hidden", minHeight: 135, marginTop: 17, padding: "17px", borderRadius: 21, background: "linear-gradient(135deg, #104438, #0B7156)", color: "white", boxShadow: "0 12px 25px #0A5F4533" }}><div style={{ position: "absolute", inset: 0, background: "radial-gradient(circle at 10% 20%, #8BE9C236, transparent 35%)" }} /><div style={{ position: "relative", display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}><div><div style={{ fontFamily: ui, fontSize: 10, opacity: 0.78, fontWeight: 700 }}>الصلاة القادمة</div><div style={{ marginTop: 3, fontFamily: ui, fontSize: 23, fontWeight: 900 }}>العصر</div></div><span style={{ fontSize: 20, color: gold }}>☀</span></div><div style={{ position: "relative", direction: "ltr", marginTop: 14, fontFamily: ui, fontSize: 26, fontWeight: 900, letterSpacing: 1.5 }}>{`٠٢:٤٣:${sec.toLocaleString("ar-EG").padStart(2, "٠")}`}</div><div style={{ position: "relative", height: 5, marginTop: 10, borderRadius: 5, background: "#FFFFFF33" }}><div style={{ width: "61%", height: 5, borderRadius: 5, background: gold }} /></div></div><div style={{ marginTop: 17, padding: "13px", borderRadius: 16, background: "#FFFFFF", border: "1px solid #E6EFEA" }}><div style={{ fontFamily: ui, color: dark, fontSize: 11, fontWeight: 900 }}>خط اليوم</div><div style={{ marginTop: 14, display: "flex", justifyContent: "space-between", alignItems: "center" }}>{prayers.map(([name, time], i) => <div key={name} style={{ textAlign: "center", color: i === 2 ? emerald : "#88978F", fontFamily: ui, fontSize: 8, fontWeight: i === 2 ? 900 : 700 }}><div style={{ width: i === 2 ? 11 : 7, height: i === 2 ? 11 : 7, margin: "0 auto 6px", borderRadius: 9, background: i === 2 ? emerald : "#BFD0C7", boxShadow: i === 2 ? "0 0 0 4px #DCF7EA" : "none" }} />{name}<div style={{ marginTop: 3, fontSize: 7 }}>{time}</div></div>)}</div><div style={{ height: 2, margin: "9px 5px 0", background: "linear-gradient(90deg, #C8DCD2, #10B981, #C8DCD2)" }} /></div><div style={{ marginTop: 14, display: "grid", gap: 8 }}>{prayers.map(([name, time, on]) => <div key={name} style={{ height: 37, padding: "0 11px", display: "flex", alignItems: "center", borderRadius: 12, background: "#FFFFFF", border: "1px solid #EBF1ED" }}><Toggle on={on} /><div style={{ flex: 1, marginRight: 10, fontFamily: ui, color: dark, fontSize: 11, fontWeight: 800 }}>{name}</div><div style={{ color: "#6A7E74", fontFamily: ui, fontSize: 10, fontWeight: 700 }}>{time}</div></div>)}</div></div><Nav active={4} /></div>;
};

const Qibla = ({ frame }: { frame: number }) => {
  const a = interpolate(frame % 240, [0, 120], [-48, 0], { extrapolateRight: "clamp", easing: Easing.out(Easing.cubic) }); const lock = ease(frame % 240, 135, 185);
  return <div style={{ ...base, background: "#07100D", color: "white", direction: "rtl" }}><div style={{ padding: "44px 20px 0" }}><div style={{ textAlign: "center", fontFamily: ui, fontSize: 17, fontWeight: 900 }}>اتجاه القبلة</div><div style={{ marginTop: 15, color: "#B7CBC2", textAlign: "center", fontFamily: ui, fontSize: 10, fontWeight: 700 }}>الرياض، المملكة العربية السعودية</div><div style={{ width: 270, height: 270, margin: "39px auto 0", position: "relative", display: "grid", placeItems: "center", filter: `drop-shadow(0 0 ${15 + lock * 23}px #10B98155)` }}><div style={{ position: "absolute", inset: 5, borderRadius: "50%", border: "1px solid #87B7A433", background: "radial-gradient(circle, #10423455 0 8%, transparent 9% 100%)" }} />{[0, 45, 90, 135].map((d) => <div key={d} style={{ position: "absolute", width: 1, height: 267, background: "linear-gradient(#76AD9533, transparent 13%, transparent 87%, #76AD9533)", transform: `rotate(${d}deg)` }} />)}<div style={{ position: "absolute", inset: 26, borderRadius: "50%", border: "1px solid #8CC4AD44" }} /><div style={{ position: "absolute", top: 18, color: gold, fontFamily: ui, fontSize: 16, fontWeight: 900 }}>ش</div><div style={{ position: "absolute", bottom: 18, color: "#D7E7DF", fontFamily: ui, fontSize: 16, fontWeight: 900 }}>ج</div><div style={{ position: "absolute", right: 20, color: "#D7E7DF", fontFamily: ui, fontSize: 15, fontWeight: 900 }}>شر</div><div style={{ position: "absolute", left: 20, color: "#D7E7DF", fontFamily: ui, fontSize: 15, fontWeight: 900 }}>غ</div><div style={{ width: 118, height: 118, background: "conic-gradient(from 0deg, #E5C983 0 50%, #10B981 50% 100%)", clipPath: "polygon(50% 0, 74% 50%, 50% 100%, 26% 50%)", transform: `rotate(${a}deg)`, filter: "drop-shadow(0 7px 10px #00000077)" }} /><div style={{ width: 46, height: 46, position: "absolute", display: "grid", placeItems: "center", borderRadius: "50%", background: "#0A261D", border: `1px solid ${lock > 0.5 ? gold : "#70A790"}`, boxShadow: lock > 0.5 ? "0 0 0 7px #D6B56B22" : "none" }}><span style={{ color: gold, fontSize: 22 }}>⌂</span></div></div><div style={{ marginTop: 31, textAlign: "center" }}><div style={{ fontFamily: ui, fontSize: 19, fontWeight: 900 }}>{lock > 0.5 ? "تم تحديد القبلة" : "جارٍ تحديد القبلة"}</div><div style={{ marginTop: 8, color: "#A7C5B7", fontFamily: ui, fontSize: 11, fontWeight: 700 }}>١٥١° باتجاه الكعبة</div></div></div><Nav active={2} /></div>;
};

const Favorite = ({ frame }: { frame: number }) => {
  const undone = frame % 240 > 150;
  return <div style={{ ...base, background: paper, direction: "rtl" }}><div style={{ padding: "44px 21px 0" }}><div style={{ textAlign: "center", fontFamily: ui, color: dark, fontSize: 17, fontWeight: 900 }}>المفضلة</div><div style={{ marginTop: 21, padding: "16px", borderRadius: 18, background: "#FFFFFF", border: "1px solid #E5EEE9", boxShadow: "0 9px 18px #1739290E" }}><div style={{ display: "flex", alignItems: "flex-start", gap: 10 }}><div style={{ flex: 1 }}><div style={{ color: dark, fontFamily: nasakh, fontSize: 17, lineHeight: 1.6 }}>لا إله إلا الله وحده لا شريك له</div><div style={{ marginTop: 7, color: "#81918A", fontFamily: ui, fontSize: 9, fontWeight: 700 }}>أذكار الصباح</div></div><div style={{ width: 34, height: 34, display: "grid", placeItems: "center", borderRadius: 12, background: undone ? "#F3F6F4" : "#FFF0F0", color: undone ? "#9BA9A2" : "#E04E62", fontSize: 20 }}>{undone ? "♡" : "♥"}</div></div></div><div style={{ marginTop: 11, height: 60, padding: "0 14px", display: "flex", alignItems: "center", justifyContent: "space-between", borderRadius: 15, background: "#FFFFFF", border: "1px solid #EBF1ED" }}><div><div style={{ color: dark, fontFamily: nasakh, fontSize: 16 }}>سبحان الله وبحمده</div><div style={{ marginTop: 5, color: "#83928B", fontFamily: ui, fontSize: 8, fontWeight: 700 }}>ورد المساء</div></div><span style={{ color: "#E04E62", fontSize: 19 }}>♥</span></div></div><div style={{ position: "absolute", right: 15, left: 15, bottom: 86, height: 52, padding: undone ? "0" : "0 15px", display: "flex", alignItems: "center", justifyContent: undone ? "center" : "space-between", borderRadius: 14, color: undone ? emerald : "white", background: undone ? "#E8F8F0" : "#102B22", boxShadow: undone ? "none" : "0 9px 19px #00140944", fontFamily: ui, fontSize: 10, fontWeight: 900 }}><span>{undone ? "تم التراجع" : "أضيف للمفضلة"}</span>{undone ? null : <span style={{ padding: "6px 10px", borderRadius: 8, color: "#86F1C4", background: "#245A48" }}>تراجع</span>}</div><Nav active={3} /></div>;
};

const Settings = ({ frame }: { frame: number }) => {
  const t = interpolate(frame % 300, [15, 170], [0, 1], { extrapolateRight: "clamp", easing: Easing.out(Easing.cubic) }); const night = frame % 300 > 180; const bg = night ? "#0B1612" : paper; const text = night ? "#F6FBF8" : dark;
  return <div style={{ ...base, background: bg, direction: "rtl" }}><div style={{ padding: "44px 21px 0" }}><div style={{ textAlign: "center", color: text, fontFamily: ui, fontSize: 17, fontWeight: 900 }}>الإعدادات</div><div style={{ marginTop: 23, padding: "15px", borderRadius: 18, background: night ? "#13251E" : "#FFFFFF", border: `1px solid ${night ? "#1F3A30" : "#E8EFEB"}` }}><div style={{ color: text, fontFamily: ui, fontWeight: 900, fontSize: 12 }}>حجم الخط</div><div style={{ marginTop: 13, padding: "16px 13px", borderRadius: 13, textAlign: "center", color: night ? "#FFFFFF" : dark, background: night ? "#0D1B15" : "#F5FAF7", fontFamily: nasakh, fontSize: 14 + t * 13, lineHeight: 1.45 }}>أصبحنا وأصبح الملك لله</div><div style={{ height: 22, marginTop: 16, display: "flex", alignItems: "center", position: "relative" }}><div style={{ width: "100%", height: 4, background: night ? "#3B5A4C" : "#D6E5DD", borderRadius: 4 }} /><div style={{ position: "absolute", right: 0, width: `${t * 72 + 12}%`, height: 4, borderRadius: 4, background: emerald }} /><div style={{ position: "absolute", right: `${t * 72 + 12}%`, width: 19, height: 19, transform: "translateX(50%)", border: `5px solid ${emerald}`, boxSizing: "border-box", borderRadius: 12, background: "white", boxShadow: "0 2px 5px #003B2788" }} /></div><div style={{ display: "flex", justifyContent: "space-between", color: night ? "#A6BFB2" : "#87968F", fontFamily: ui, fontSize: 8, fontWeight: 800 }}><span>١٤</span><span>٣٢</span></div></div><div style={{ marginTop: 16, color: text, fontFamily: ui, fontSize: 12, fontWeight: 900 }}>المظهر</div><div style={{ height: 43, marginTop: 9, padding: 4, display: "flex", direction: "rtl", borderRadius: 14, background: night ? "#13251E" : "#EEF4F0" }}>{[["النظام", false], ["فاتح", !night], ["داكن", night]].map(([label, selected]) => <div key={label as string} style={{ flex: 1, display: "grid", placeItems: "center", borderRadius: 10, background: selected ? (night ? "#27614E" : "#FFFFFF") : "transparent", color: selected ? (night ? "#E8FFF3" : emerald) : (night ? "#A1B8AC" : "#7C8B84"), boxShadow: selected ? "0 2px 5px #05150C18" : "none", fontFamily: ui, fontSize: 10, fontWeight: 900 }}>{label as string}</div>)}</div><div style={{ marginTop: 18, padding: "12px", borderRadius: 15, background: night ? "#13251E" : "#FFFFFF", border: `1px solid ${night ? "#203A30" : "#EAF0EC"}` }}><div style={{ color: text, fontFamily: ui, fontSize: 11, fontWeight: 900 }}>لغة التطبيق</div><div style={{ marginTop: 5, color: night ? "#9AB3A7" : "#87978F", fontFamily: ui, fontSize: 9, fontWeight: 700 }}>العربية</div></div></div><Nav active={5} /></div>;
};

const Splash = ({ frame }: { frame: number }) => {
  const opened = ease(frame, 7, 65);
  return <div style={{ ...base, display: "grid", placeItems: "center", background: "radial-gradient(circle at 50% 35%, #159D74, #083C2E)", opacity: 1 - opened }}><div style={{ textAlign: "center", color: "white" }}><Brand size={59} reverse /><div style={{ marginTop: 16, fontFamily: ui, fontSize: 14, fontWeight: 800, opacity: 0.72 }}>رفيق الذكر اليومي</div></div></div>;
};

export const Screen = ({ shot, frame }: { shot: Shot; frame: number }) => shot === "hero" ? <><Home frame={frame} /><Splash frame={frame % 240} /></> : shot === "category" ? <Category frame={frame} /> : shot === "counter" ? <Counter frame={frame} /> : shot === "quran" ? <Quran frame={frame} /> : shot === "prayer" ? <Prayer frame={frame} /> : shot === "qibla" ? <Qibla frame={frame} /> : shot === "favorite" ? <Favorite frame={frame} /> : shot === "settings" ? <Settings frame={frame} /> : <Home frame={frame} />;

export const Device = ({ phone, children, scale, x, y, rotation, opacity = 1, off = false }: { phone: Phone; children: React.ReactNode; scale: number; x: number; y: number; rotation: number; opacity?: number; off?: boolean }) => {
  const w = 430 * scale;
  const h = 880 * scale;
  const bezel = Math.max(5, 10 * scale);
  const iphone = phone === "iphone";
  const screenScale = (w - 2 * bezel) / 430;
  return (
    <div style={{ position: "absolute", left: x, top: y, width: w, height: h, opacity, transform: `translate(-50%, -50%) rotate(${rotation}deg)`, transformOrigin: "center", filter: `drop-shadow(0 ${25 * scale}px ${28 * scale}px #0000005C)` }}>
      <div style={{ position: "absolute", inset: 0, padding: bezel, boxSizing: "border-box", borderRadius: (iphone ? 58 : 38) * scale, background: iphone ? "linear-gradient(120deg, #3A4B47, #101713 13%, #000 55%, #4B5E59)" : "linear-gradient(110deg, #5A655F, #141B18 11%, #010201 60%, #46534D)", boxShadow: "inset 1px 0 0 #FFFFFF77, inset -1px -1px 0 #010503" }}>
        <div style={{ position: "relative", width: "100%", height: "100%", overflow: "hidden", borderRadius: (iphone ? 49 : 29) * scale, background: "#07110D" }}>
          <div style={{ position: "absolute", inset: 0, zIndex: 1, overflow: "hidden", background: "#FBF8F1" }}>
            <div style={{ width: 430, height: 880, position: "relative", zoom: screenScale }}>{children}</div>
          </div>
          <div style={{ position: "absolute", inset: 0, opacity: off ? 1 : 0, zIndex: 10, background: "linear-gradient(135deg, #050705, #101813)" }} />
          {iphone ? <div style={{ position: "absolute", top: 10 * scale, left: "50%", zIndex: 13, width: 116 * scale, height: 31 * scale, transform: "translateX(-50%)", borderRadius: 18 * scale, background: "#030303", boxShadow: "inset 0 1px 0 #373737" }} /> : <div style={{ position: "absolute", top: 10 * scale, left: "50%", zIndex: 13, width: 16 * scale, height: 16 * scale, transform: "translateX(-50%)", borderRadius: "50%", background: "#020202", border: `${scale}px solid #1C2A26` }} />}
          <div style={{ position: "absolute", inset: 0, zIndex: 12, opacity: off ? 0 : 0.22, background: "linear-gradient(116deg, rgba(255,255,255,.36) 0%, rgba(255,255,255,.08) 12%, transparent 25%, transparent 61%, rgba(255,255,255,.07) 82%, transparent 100%)" }} />
        </div>
      </div>
    </div>
  );
};

const Touch = ({ x, y, scale, opacity }: { x: number; y: number; scale: number; opacity: number }) => <div style={{ position: "absolute", left: x, top: y, width: 44 * scale, height: 44 * scale, transform: "translate(-50%, -50%)", opacity, borderRadius: "50%", background: "radial-gradient(circle at 35% 30%, #FFE9D6, #C48663 58%, #6C3E2D)", boxShadow: "0 7px 16px #12080377, inset 2px 2px 5px #FFF8" }}><span style={{ position: "absolute", inset: -9 * scale, border: `${2 * scale}px solid #FFFFFF99`, borderRadius: "50%" }} /></div>;

const Studio = ({ frame }: { frame: number }) => {
  const drift = Math.sin(frame / 180) * 3;
  return <AbsoluteFill style={{ overflow: "hidden", background: "linear-gradient(135deg, #18211D 0%, #0B100E 48%, #1F2925 100%)" }}><div style={{ position: "absolute", inset: "-12%", transform: `translate(${drift}px, ${-drift}px)`, backgroundImage: "linear-gradient(112deg, transparent 0 43%, #ffffff08 43.1% 43.22%, transparent 43.3% 100%), radial-gradient(circle at 16% 26%, #10B98126, transparent 24%), radial-gradient(circle at 84% 70%, #D6B56B20, transparent 19%)" }} /><div style={{ position: "absolute", left: "-10%", right: "-10%", bottom: "-26%", height: "53%", borderRadius: "50% 50% 0 0", background: "radial-gradient(ellipse at 50% 5%, #30413A, #0E1612 67%)", boxShadow: "0 -3px 0 #FFFFFF0C" }} /><div style={{ position: "absolute", left: "9%", right: "9%", bottom: "11%", height: 1, background: "#D6B56B33" }} /></AbsoluteFill>;
};

const Badge = ({ circle }: { circle: boolean }) => <div style={{ minWidth: 156, height: 48, padding: "0 14px", display: "flex", gap: 10, alignItems: "center", justifyContent: "center", borderRadius: 14, color: "white", background: "#0B0C0BE8", border: "1px solid #FFFFFF55", boxShadow: "0 5px 15px #00000055" }}><span style={{ fontSize: 24 }}>{circle ? "●" : "▶"}</span><span style={{ fontFamily: ui, fontSize: 10, fontWeight: 900 }}>متجر التطبيقات</span></div>;

const Close = ({ frame, portrait }: { frame: number; portrait: boolean }) => {
  const a = spring({ frame: Math.max(0, frame - 2140), fps: 60, config: { damping: 18, stiffness: 95, mass: 0.8 } });
  return <div style={{ position: "absolute", left: "50%", top: portrait ? "68%" : "50%", zIndex: 40, opacity: a, textAlign: "center", transform: `translate(-50%, -50%) scale(${0.82 + a * 0.18})` }}><Brand size={portrait ? 88 : 92} reverse /><div style={{ marginTop: 15, color: "#D6E8DF", whiteSpace: "nowrap", fontFamily: ui, fontSize: portrait ? 22 : 24, fontWeight: 700 }}>اذكر الله... يطمئن قلبك</div><div style={{ marginTop: 25, display: "flex", gap: 10, justifyContent: "center" }}><Badge circle /><Badge circle={false} /></div></div>;
};

export const AlMufradunPromo: React.FC = () => {
  const frame = useCurrentFrame(); const { width, height } = useVideoConfig(); const portrait = height > width; const shot = shotAt(frame); const local = frame % 240; const final = shot === "closing";
  const scale = portrait ? 1.6 : width / 2400; const ix = portrait ? width * 0.5 : width * 0.3; const iy = portrait ? height * 0.3 : height * 0.54; const gx = portrait ? width * 0.5 : width * 0.7; const gy = portrait ? height * 0.62 : height * 0.51;
  const rotation = shot === "qibla" ? interpolate(local, [0, 85, 185], [-8, 8, 0], { extrapolateRight: "clamp", easing: Easing.inOut(Easing.quad) }) : 0; const dolly = interpolate(frame, [0, 180], [1.12, 1], { extrapolateRight: "clamp", easing: Easing.out(Easing.cubic) }); const end = ease(frame, 2100, 2185);
  const touch = shot === "category" ? [ix + (portrait ? 170 : 95) * scale, iy - 150 * scale] : shot === "counter" ? [ix, iy + 75 * scale] : shot === "quran" ? [gx, gy + 195 * scale] : shot === "favorite" ? [ix + 132 * scale, iy - 100 * scale] : null;
  return <AbsoluteFill style={{ direction: "rtl" }}><style>{`@font-face{font-family:AlMufradunUI;src:url('${staticFile("fonts/YearRegular.otf")}') format('opentype');font-weight:400 900;font-display:block}@font-face{font-family:AlMufradunUI;src:url('${staticFile("fonts/YearBlack.otf")}') format('opentype');font-weight:900;font-display:block}@font-face{font-family:AlMufradunNasakh;src:url('${staticFile("fonts/Alnasakh.ttf")}') format('truetype');font-display:block}@font-face{font-family:AlMufradunQuran;src:url('${staticFile("fonts/UthmanicHafs.ttf")}') format('truetype');font-display:block}`}</style><Studio frame={frame} /><div style={{ position: "absolute", inset: 0, transform: `scale(${dolly})`, transformOrigin: "center" }}><Device phone="iphone" scale={scale} x={ix} y={iy} rotation={shot === "hero" ? -5 : rotation} opacity={final ? 1 - end : 1} off={final && end > 0.38}><Screen shot={shot} frame={frame} /></Device><Device phone="galaxy" scale={scale} x={gx} y={gy} rotation={shot === "hero" ? 5 : -rotation * 0.7} opacity={portrait ? (final ? 1 - end : 0.82) : (final ? 1 - end : 1)} off={final && end > 0.38}><Screen shot={shot} frame={frame + 18} /></Device></div>{touch && !final ? <Touch x={touch[0]} y={touch[1]} scale={scale} opacity={0.82} /> : null}{shot === "qibla" ? <div style={{ position: "absolute", left: "50%", top: portrait ? "88%" : "85%", transform: "translateX(-50%)", color: "#C8E5D8", whiteSpace: "nowrap", fontFamily: ui, fontSize: portrait ? 42 : 25, fontWeight: 900, letterSpacing: 1 }}>قبلةٌ أقرب إلى قلبك</div> : null}{final ? <Close frame={frame} portrait={portrait} /> : null}<Audio src={staticFile("ambient.wav")} volume={(f) => interpolate(f, [0, 120, 2220, 2460], [0, 0.34, 0.3, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" })} />{[288, 335, 383, 770, 904, 1180, 1390, 1630, 1890].map((from) => <Sequence key={from} from={from} durationInFrames={12}><Audio src={staticFile("ui-click.wav")} volume={0.19} /></Sequence>)}</AbsoluteFill>;
};
